#MQTT Global Information Advertise Enable ( "no" or "yes")
MQTT_ADV_INFO_GLOBAL_ENABLE=no
#MQTT Global Information Advertise service to start on boot ( "no" or "yes")
MQTT_ADV_INFO_GLOBAL_BOOT=no
#MQTT Global Information Advertise service crontab start ( "no" or "yes")
MQTT_ADV_INFO_GLOBAL_CRON=no
#MQTT Global Information Advertise service crontab. Default every hour
MQTT_ADV_INFO_GLOBAL_CRONTAB=0 * * * *
#MQTT Global Information Advertise service crontab. Default every hour 
MQTT_ADV_INFO_GLOBAL_TOPIC=info/global

#Home Assistant Enable ( "no" or "yes")
HOMEASSISTANT_ENABLE=no
#Home Assistant MQTT discovery advertise service to start on boot ( "no" or "yes")
HOMEASSISTANT_BOOT=no
#Home Assistant MQTT discovery crontab start ( "no" or "yes")
HOMEASSISTANT_CRON=no
#Home Assistant MQTT discovery crontab. Default every hour
HOMEASSISTANT_CRONTAB=0 * * * *

# Don't use double quote " 
#Home Assistant discovery topic, should be "homeassistant"
HOMEASSISTANT_MQTT_PREFIX=homeassistant

# Device Unique name - It used by Homeassistant for identify the Device
HOMEASSISTANT_NAME=Yi Camera
# Device unique id - It used by Homeassistant for identify the Device (DONT USE SPACE)
HOMEASSISTANT_IDENTIFIERS=yi-cam
# Device Manufactuer - It used by Homeassistant
HOMEASSISTANT_MANUFACTURER=YI
# Device Model  - It used by Homeassistant
HOMEASSISTANT_MODEL=YI Hack
